### ISSUE TITLE
自動テストが不安定なのを治す

### ISSUE THREAD

**Issue by Saigo1997** [Saigo1997/shiori#108]
テストが頻繁に落ちるが再実行すると通ったりする。

**Comment by Saigo1997** [comment]
```
  1) playlist プレイリスト1を削除(実行)
     Failure/Error: expect(page).to_not have_content('プレイリスト1')
       expected not to find text "プレイリスト1" in "menu\n新規動画\n新規プレイリスト\nログアウト\nShiori\nperson\nユーザー設定\nlist\n動画一覧\nadd\n新規動画\nplaylist_play\nプレイリスト1\nplaylist_play\nプレイリスト2\nplaylist_add\n新規プレイリスト\nexit_to_app\nログアウト\n未視聴\n視聴中\n視聴済み\n今は見ない\n不明\n残り動画時間\n動画時間\narrow_upward\n00:00:00\nmedia_1\n動画時間が登録されていません\n00:00:00\nmedia_2\n動画時間が登録されていません\n00:00:00\nmedia_3\n動画時間が登録されていません"
     # ./spec/system/playlist_spec.rb:110:in `block (2 levels) in <top (required)>'

  2) playlist プレイリストに戻る
     Failure/Error: expect(page).to have_content('プレイリストに追加しました')
       expected to find text "プレイリストに追加しました" in "menu\n新規動画\n新規プレイリスト\nログアウト\nShiori\n一覧に戻る\n00:00:00\nmedia_1\nmore_vert\n今は見ないに入れる\n＋時間 ＋画像 プレイリスト\nプレイリスト\nプレイリスト1\nプレイリスト2\n閉じる"
     # ./spec/system/playlist_spec.rb:45:in `add_media_to_playlist'
     # ./spec/system/playlist_spec.rb:114:in `block (2 levels) in <top (required)>'
```
